[package]
name = "monolog-algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
rand = "0.8.5"
thiserror = "2.0.9"

[dev-dependencies]
criterion = "0.5.1"
